// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/antifraud.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AntiFraudService_AnalyzeRiskScore_FullMethodName = "/antifraud.AntiFraudService/AnalyzeRiskScore"
	AntiFraudService_BatchChargeback_FullMethodName  = "/antifraud.AntiFraudService/BatchChargeback"
)

// AntiFraudServiceClient is the client API for AntiFraudService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AntiFraudServiceClient interface {
	// Unary: Validação imediata de uma transação
	AnalyzeRiskScore(ctx context.Context, in *RiskRequest, opts ...grpc.CallOption) (*RiskResponse, error)
	// Client Streaming: Recebe um lote de estornos de uma vez
	BatchChargeback(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChargebackRequest, ChargebackSummary], error)
}

type antiFraudServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAntiFraudServiceClient(cc grpc.ClientConnInterface) AntiFraudServiceClient {
	return &antiFraudServiceClient{cc}
}

func (c *antiFraudServiceClient) AnalyzeRiskScore(ctx context.Context, in *RiskRequest, opts ...grpc.CallOption) (*RiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskResponse)
	err := c.cc.Invoke(ctx, AntiFraudService_AnalyzeRiskScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiFraudServiceClient) BatchChargeback(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChargebackRequest, ChargebackSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AntiFraudService_ServiceDesc.Streams[0], AntiFraudService_BatchChargeback_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChargebackRequest, ChargebackSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AntiFraudService_BatchChargebackClient = grpc.ClientStreamingClient[ChargebackRequest, ChargebackSummary]

// AntiFraudServiceServer is the server API for AntiFraudService service.
// All implementations must embed UnimplementedAntiFraudServiceServer
// for forward compatibility.
type AntiFraudServiceServer interface {
	// Unary: Validação imediata de uma transação
	AnalyzeRiskScore(context.Context, *RiskRequest) (*RiskResponse, error)
	// Client Streaming: Recebe um lote de estornos de uma vez
	BatchChargeback(grpc.ClientStreamingServer[ChargebackRequest, ChargebackSummary]) error
	mustEmbedUnimplementedAntiFraudServiceServer()
}

// UnimplementedAntiFraudServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAntiFraudServiceServer struct{}

func (UnimplementedAntiFraudServiceServer) AnalyzeRiskScore(context.Context, *RiskRequest) (*RiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeRiskScore not implemented")
}
func (UnimplementedAntiFraudServiceServer) BatchChargeback(grpc.ClientStreamingServer[ChargebackRequest, ChargebackSummary]) error {
	return status.Error(codes.Unimplemented, "method BatchChargeback not implemented")
}
func (UnimplementedAntiFraudServiceServer) mustEmbedUnimplementedAntiFraudServiceServer() {}
func (UnimplementedAntiFraudServiceServer) testEmbeddedByValue()                          {}

// UnsafeAntiFraudServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AntiFraudServiceServer will
// result in compilation errors.
type UnsafeAntiFraudServiceServer interface {
	mustEmbedUnimplementedAntiFraudServiceServer()
}

func RegisterAntiFraudServiceServer(s grpc.ServiceRegistrar, srv AntiFraudServiceServer) {
	// If the following call panics, it indicates UnimplementedAntiFraudServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AntiFraudService_ServiceDesc, srv)
}

func _AntiFraudService_AnalyzeRiskScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiFraudServiceServer).AnalyzeRiskScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiFraudService_AnalyzeRiskScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiFraudServiceServer).AnalyzeRiskScore(ctx, req.(*RiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiFraudService_BatchChargeback_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AntiFraudServiceServer).BatchChargeback(&grpc.GenericServerStream[ChargebackRequest, ChargebackSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AntiFraudService_BatchChargebackServer = grpc.ClientStreamingServer[ChargebackRequest, ChargebackSummary]

// AntiFraudService_ServiceDesc is the grpc.ServiceDesc for AntiFraudService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AntiFraudService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antifraud.AntiFraudService",
	HandlerType: (*AntiFraudServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeRiskScore",
			Handler:    _AntiFraudService_AnalyzeRiskScore_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchChargeback",
			Handler:       _AntiFraudService_BatchChargeback_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/antifraud.proto",
}
