// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/antifraud.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskRequest) Reset() {
	*x = RiskRequest{}
	mi := &file_proto_antifraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskRequest) ProtoMessage() {}

func (x *RiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_antifraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskRequest.ProtoReflect.Descriptor instead.
func (*RiskRequest) Descriptor() ([]byte, []int) {
	return file_proto_antifraud_proto_rawDescGZIP(), []int{0}
}

func (x *RiskRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RiskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RiskRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RiskRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type RiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RiskScore     int32                  `protobuf:"varint,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	SecurityHash  string                 `protobuf:"bytes,5,opt,name=security_hash,json=securityHash,proto3" json:"security_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskResponse) Reset() {
	*x = RiskResponse{}
	mi := &file_proto_antifraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskResponse) ProtoMessage() {}

func (x *RiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_antifraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskResponse.ProtoReflect.Descriptor instead.
func (*RiskResponse) Descriptor() ([]byte, []int) {
	return file_proto_antifraud_proto_rawDescGZIP(), []int{1}
}

func (x *RiskResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RiskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RiskResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *RiskResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RiskResponse) GetSecurityHash() string {
	if x != nil {
		return x.SecurityHash
	}
	return ""
}

type ChargebackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargebackRequest) Reset() {
	*x = ChargebackRequest{}
	mi := &file_proto_antifraud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargebackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargebackRequest) ProtoMessage() {}

func (x *ChargebackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_antifraud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargebackRequest.ProtoReflect.Descriptor instead.
func (*ChargebackRequest) Descriptor() ([]byte, []int) {
	return file_proto_antifraud_proto_rawDescGZIP(), []int{2}
}

func (x *ChargebackRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ChargebackRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ChargebackRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type ChargebackSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalProcessed int32                  `protobuf:"varint,1,opt,name=total_processed,json=totalProcessed,proto3" json:"total_processed,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChargebackSummary) Reset() {
	*x = ChargebackSummary{}
	mi := &file_proto_antifraud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargebackSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargebackSummary) ProtoMessage() {}

func (x *ChargebackSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_antifraud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargebackSummary.ProtoReflect.Descriptor instead.
func (*ChargebackSummary) Descriptor() ([]byte, []int) {
	return file_proto_antifraud_proto_rawDescGZIP(), []int{3}
}

func (x *ChargebackSummary) GetTotalProcessed() int32 {
	if x != nil {
		return x.TotalProcessed
	}
	return 0
}

func (x *ChargebackSummary) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_antifraud_proto protoreflect.FileDescriptor

const file_proto_antifraud_proto_rawDesc = "" +
	"\n" +
	"\x15proto/antifraud.proto\x12\tantifraud\"\x84\x01\n" +
	"\vRiskRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\"\xa9\x01\n" +
	"\fRiskResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x05R\triskScore\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12#\n" +
	"\rsecurity_hash\x18\x05 \x01(\tR\fsecurityHash\"q\n" +
	"\x11ChargebackRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\"V\n" +
	"\x11ChargebackSummary\x12'\n" +
	"\x0ftotal_processed\x18\x01 \x01(\x05R\x0etotalProcessed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa8\x01\n" +
	"\x10AntiFraudService\x12C\n" +
	"\x10AnalyzeRiskScore\x12\x16.antifraud.RiskRequest\x1a\x17.antifraud.RiskResponse\x12O\n" +
	"\x0fBatchChargeback\x12\x1c.antifraud.ChargebackRequest\x1a\x1c.antifraud.ChargebackSummary(\x01B\x05Z\x03/pbb\x06proto3"

var (
	file_proto_antifraud_proto_rawDescOnce sync.Once
	file_proto_antifraud_proto_rawDescData []byte
)

func file_proto_antifraud_proto_rawDescGZIP() []byte {
	file_proto_antifraud_proto_rawDescOnce.Do(func() {
		file_proto_antifraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_antifraud_proto_rawDesc), len(file_proto_antifraud_proto_rawDesc)))
	})
	return file_proto_antifraud_proto_rawDescData
}

var file_proto_antifraud_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_antifraud_proto_goTypes = []any{
	(*RiskRequest)(nil),       // 0: antifraud.RiskRequest
	(*RiskResponse)(nil),      // 1: antifraud.RiskResponse
	(*ChargebackRequest)(nil), // 2: antifraud.ChargebackRequest
	(*ChargebackSummary)(nil), // 3: antifraud.ChargebackSummary
}
var file_proto_antifraud_proto_depIdxs = []int32{
	0, // 0: antifraud.AntiFraudService.AnalyzeRiskScore:input_type -> antifraud.RiskRequest
	2, // 1: antifraud.AntiFraudService.BatchChargeback:input_type -> antifraud.ChargebackRequest
	1, // 2: antifraud.AntiFraudService.AnalyzeRiskScore:output_type -> antifraud.RiskResponse
	3, // 3: antifraud.AntiFraudService.BatchChargeback:output_type -> antifraud.ChargebackSummary
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_antifraud_proto_init() }
func file_proto_antifraud_proto_init() {
	if File_proto_antifraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_antifraud_proto_rawDesc), len(file_proto_antifraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_antifraud_proto_goTypes,
		DependencyIndexes: file_proto_antifraud_proto_depIdxs,
		MessageInfos:      file_proto_antifraud_proto_msgTypes,
	}.Build()
	File_proto_antifraud_proto = out.File
	file_proto_antifraud_proto_goTypes = nil
	file_proto_antifraud_proto_depIdxs = nil
}
